#!/bin/sh

rm -f src/*.o src/*.so src/symbols.rds

rm -rf vignettes/auto/ vignettes/rmd/pinp.cls vignettes/rmd/jss.bst

for e in log aux out tex blg bbl xwm; do
    rm -f vignettes/rmd/${e}
done

find . -name \*~ -exec rm {} \;

