#!/bin/sh

rm -f src/*.o src/*.so src/symbols.rds

rm -rf vignettes/auto/ vignettes/*.log vignettes/*.aux vignettes/*.out vignettes/*.tex \
       vignettes/*.blg vignettes/*.bbl

find . -name \*~ -exec rm {} \;

